int cc_send(unsigned char *b, int len);
uint16_t reg_get(int base, int reg);
int reg_set(int base, int reg, int v);
uint16_t cc_get(int reg);
int cc_set(int reg, int v);
uint16_t mmc_get(int reg);
int mmc_set(int reg, int v);
uint32_t _cc_read_pair(int r1, int r2);
uint64_t _cc_read_triple(int r1, int r2, int r3);
uint32_t cc_read_obus_(void);
uint16_t cc_read_scratch(void);
uint32_t bitmask(int wid);
uint64_t ir_pair(int field, uint32_t val);
int cc_write_md_1s(void);
int cc_write_md_0s(void);
int cc_report_basic_regs(void);
int cc_report_pc(uint32_t *ppc);
int cc_report_pc_and_md(uint32_t *ppc);
int cc_report_pc_and_ir(uint32_t *ppc);
int cc_report_pc_md_ir(uint32_t *ppc);
int cc_report_status(void);
int cc_pipe(void);
int cc_pipe2(void);
int cc_setup_map(void);
int cc_report_ide_regs(void);
int _test_scratch(uint16_t v);
int cc_test_scratch(void);
int _test_ir(uint64_t isn);
int cc_test_ir(void);
